newproject/miapp/urls.py
from django.conf.urls import url
from miapp import views

# TEMPLATE TAGGING
app_name = 'miapp'

urlpatterns = [
	url('relative/', views.relative, name='relative'),
	url('other/', views.other, name='other'),
]

newproject/newproject/urls.py
from django.contrib import admin
from django.urls import path, include
from miapp import views

urlpatterns = [
	path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('miapp/', include('miapp.urls')),
]

newproject/miapp/models.py
from django.db import models

# Create your models here.

newproject/miapp/views.py
from django.shortcuts import render


def index(request):
	my_dict = {'string':'hello world', 'num':100}
	return render(request, 'miapp/index.html', my_dict)

def other(request):
	return render(request, 'miapp/other.html')

def relative(request):	
	return render(request, 'miapp/relative_url_templates.html')

newproject/templates/miapp/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container-fluid">
		  <a class="navbar-brand" href="{% url 'index' %}">Brand</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		    <ul class="navbar-nav">
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'miapp:other' %}">Other</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'miapp:relative' %}">Relative</a>
		      </li>
		    </ul>
		  </div>
		</div>
	</nav>

	<div class="container">
		{% block body_block %}
			<!-- Anything outside of this will be inherited -->
		{% endblock %}
	</div>

	<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script> -->


</body>
</html>

newproject/templates/miapp/index.html
<!DOCTYPE html>
{% extends "miapp/base.html" %}
	
	{% block body_block %}

		<h1>Welcome to INDEX</h1>
		<h2>{{ string|cut:'l' }}</h2>
		<h2>{{ num|add:99 }}</h2>

	{% endblock %}

newproject/templates/miapp/other.html
<!DOCTYPE html>
{% extends "miapp/base.html" %}
	
	{% block body_block %}

		<h1>Hey this is Other Page</h1>
		<h2>This is an example of template inheritance!</h2>

	{% endblock %}

newproject/templates/miapp/relative_url_templates.html
<!DOCTYPE html>
{% extends "miapp/base.html" %}
	
	{% block body_block %}

		<h1>Welcome to RELATIVE URL TEMPLATE</h1>

	{% endblock %}